name: AWS CodeCommit Mirror

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    #Every 15 minutes
    - cron: "*/15 * * * *"

#Enviroment Variables
env:
  GH_API_TOKEN: ${{ secrets.GH_INTEGRATIONS_AWS_COMMIT_MIRROR }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SSH_KEY_ID: ${{ secrets.AWS_SSH_KEY_ID }}

jobs:
  mirroring:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipenv & Dependencies
      run: |
        pip install pipenv
        pipenv install

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace

    - name: Copy SSH directory to home
      run: |
        mkdir -p ~/work/_temp/_github_home/
        cp -ar ~/.ssh ~/work/_temp/_github_home/

    - name: Mirror Github Repositories to AWS CodeCommit
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"
        pipenv run python3 src/github-aws-commit-mirror.py

