name: AWS CodeCommit Mirror

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, delete]

#Enviroment Variables
env:
  GH_API_TOKEN: ${{ secrets.GH_INTEGRATIONS_AWS_COMMIT_MIRROR }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SSH_KEY_ID: ${{ secrets.AWS_SSH_KEY_ID }}

jobs:
  mirroring:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install pipenv
      run: |
        # python -m pip install --upgrade pip
        pip install pipenv
        pipenv install PyGithub==1.46
        pipenv install boto3==1.10.41
        pipenv install backports.weakref
        pipenv install backports.functools_lru_cache
        pipenv install backports.shutil_get_terminal_size

    # - name: cache pipenv
    #   id: cache-pipenv
    #   uses: actions/cache@v2
    #   with:
    #     path: api/.venv
    #     key: ${{ runner.os }}-3.8-pipenv-${{ hashFiles('api/Pipfile.lock') }}

    # - name: install dependencies
    #   working-directory: /home/runner/work/github-aws-commit-mirror/github-aws-commit-mirror/
    #   if: steps.cache-pipenv.outputs.cache-hit != 'true'
    #   env:
    #     PIPENV_VENV_IN_PROJECT: 1
    #   run: |
    #     pipenv install --dev

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace

    - name: copy to home
      run: |
        mkdir -p ~/work/_temp/_github_home/
        cp -ar ~/.ssh ~/work/_temp/_github_home/

    # - uses: actions/checkout@v3
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.8'

    # - name: Install Dependencies
    #   run: |
    #     sudo pip3 install pipenv
    #     pipenv install PyGithub==1.46
    #     pipenv install boto3==1.10.41
    #     pipenv install backports.weakref
    #     pipenv install backports.functools_lru_cache
    #     pipenv install backports.shutil_get_terminal_size
    #     pip install --upgrade setuptools
    #     pip install backports.functools-lru-cache
    #     pip install backports.weakref
    #     sudo pip install pipenv
    #     pipenv install

    - uses: actions/checkout@v2
    - name: Mirror Github Repositories to AWS CodeCommit
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"
        pipenv run python3 src/github-aws-commit-mirror.py

